### ISSUE TITLE
Resignation of maintenance

### ISSUE THREAD

**Issue by twolfson** [uber-archive/image-diff#55]
I'm resigning as a maintainer of this package due to the tedium/frustration at resolving simple issues (e.g. playing PR telephone). I barely use this repo any more as there are simpler dependency-less solutions (e.g. `looks-same`, `pixelmatch`).

I don't believe there are any other maintainers so I believe this repo should be deprecated to `uber-archive` and we can update its README to state deprecation as well as link to alternative libraries. I'm happy to submit a PR for the latter half of this.

Thoughts?

/cc @mlmorg

**Comment by mlmorg** [comment]
Hey @twolfson, we've moved this to `uber-archive` as you suggested. Let me know if you want to update the readme, or if you'd like me to.

**Comment by twolfson** [comment]
Great, thanks @mlmorg. I've opened #56 to complete the README updates for GitHub and `npm`

**Comment by oliviertassinari** [comment]
for what that's worth, I have forked this repository as [image-difference](https://github.com/argos-ci/image-difference#benchmark) modernizing it (ES2015, async/await, jest, benchmark, multiple implementations).

**Comment by jasperkuperus** [comment]
What's the status on this PR? Would be nice to merge it, will save people who stumble upon this library some time.

**Comment by mlmorg** [comment]
Sorry for the delay! The PR is now merged!
